import { Inter } from 'next/font/google';
import '@/app/globals.css';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Pokemon list',
  description: 'Generated by me',
};

export default function PokemonsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className='bg-red-500 p-10 '>{children}</div>;
}
